### ISSUE TITLE
MLPerf Inference Submission TODO List

### ISSUE THREAD

**Issue by byounghak36** [ltechkorea/inference_results_v1.0#25]
각 항목의 설명은 [Wiki](https://github.com/ltechkorea/inference_results_v1.0/wiki/MLPerf-Inference-v1.1-Submission-How-to#mlperf-inference-v11) 참조

- [x] #26
- [x] #27
- [x] README.md PR
- [x] Create a branch
- [x] Run the submission checker
- [x] Mail transfer to chairman
- [ ] Push the changes
- [ ] Create a pull request
